language: node_js
node_js:
   - "0.8"
   - "0.6"
notifications:
   email:
     - xiangnan.zhang@pactera.com
     - zhuang.miao@pactera.com
notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
    on_success:always
    on_failure:always
